FROM python:3.13-slim

WORKDIR /app

RUN apt-get update && apt-get install -y git
RUN git clone https://github.com/NeatyNut/aiagent.git
# COPY .env /app/aiagent/.env

# 가상환경 생성
RUN python3 -m venv /app/venv
# 가상환경 내 pip 업데이트 및 requirements 설치
RUN /bin/bash -c "source /app/venv/bin/activate && pip install --upgrade pip && pip install --no-cache-dir -r /app/aiagent/requirements.txt"

# 실행 시 가상환경 활성화 후 실행하도록 설정
ENV PATH="/app/venv/bin:$PATH"